### ISSUE TITLE
missing LICENSE file

### ISSUE THREAD

**Issue by LookingSharp** [AltBeacon/windows-beacon-library#4]
Thanks for creating this project!  Pretty cool.  Could you add a top level license file for this project? I see it in your other AltBeacon repos, but it is missing in this one.

Thanks!

**Comment by csexton** [comment]
Thanks for pointing this out @LookingSharp, that is a big oversight.

This is licensed the same way the Android Beacon Library, with the Apache License Version 2.0. I'll update the repo shortly.
